# Generated by Django 4.2.6 on 2024-04-06 08:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bulletin', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('date_and_time_bulletin', models.DateTimeField(auto_now_add=True)),
                ('author_bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=255)),
                ('text_news', models.TextField()),
                ('date_and_time_news', models.DateTimeField(auto_now_add=True)),
                ('category_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('date_and_time_сomment', models.DateTimeField(auto_now_add=True)),
                ('acceptance_flag', models.BooleanField(default=False)),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_comments', to=settings.AUTH_USER_MODEL)),
                ('bulletin_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.bulletin')),
            ],
        ),
        migrations.AddField(
            model_name='bulletin',
            name='category_bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.category'),
        ),
    ]
