# Generated by Django 4.2.6 on 2024-04-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=255)),
                ('text_news', models.TextField()),
                ('date_and_time_news', models.DateTimeField(auto_now_add=True)),
                ('category_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.category')),
            ],
        ),
    ]
