# Generated by Django 4.2.6 on 2024-04-03 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bulletin', models.CharField(max_length=255)),
                ('text_bulletin', models.TextField()),
                ('date_and_time_bulletin', models.DateTimeField(auto_now_add=True)),
                ('author_bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.bulletin')),
            ],
        ),
        migrations.AddField(
            model_name='bulletin',
            name='category_bulletin',
            field=models.ManyToManyField(through='bulletin.BulletinCategory', to='bulletin.category'),
        ),
    ]
