# Generated by Django 4.2.6 on 2024-04-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0003_bulletin_bulletincategory_bulletin_category_bulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('date_and_time_сomment', models.DateTimeField(auto_now_add=True)),
                ('acceptance_flag', models.BooleanField(default=False)),
                ('author_bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_comments', to=settings.AUTH_USER_MODEL)),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_comments', to=settings.AUTH_USER_MODEL)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.bulletin')),
            ],
        ),
    ]
